<!DOCTYPE html>
<html>
    <head>
        <title>DevOps : Exception Handling</title>
        <link rel="stylesheet" href="styles/site.css" type="text/css" />
        <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>

    <body class="theme-default aui-theme-default">
        <div id="page">
            <div id="main" class="aui-page-panel">
                <div id="main-header">
                    <div id="breadcrumb-section">
                        <ol id="breadcrumbs">
                            <li class="first">
                                <span><a href="index.html">DevOps</a></span>
                            </li>
                                                    <li>
                                <span><a href="DevOps-Home_603226548.html">DevOps Home</a></span>
                            </li>
                                                    <li>
                                <span><a href="Tutorials_278921431.html">Tutorials</a></span>
                            </li>
                                                    <li>
                                <span><a href="Spring-Boot_278888737.html">Spring Boot</a></span>
                            </li>
                                                    <li>
                                <span><a href="Overrides_290029797.html">Overrides</a></span>
                            </li>
                                                </ol>
                    </div>
                    <h1 id="title-heading" class="pagetitle">
                                                <span id="title-text">
                            DevOps : Exception Handling
                        </span>
                    </h1>
                </div>

                <div id="content" class="view">
                    <div class="page-metadata">
                        
        
    
        
    
        
        
            Created by <span class='author'> Nicholas Guner</span>, last modified on Apr 19, 2020
                        </div>
                    <div id="main-content" class="wiki-content group">
                    <p>Consider the following situation. In the middle of some function, we would like to invoke a PeopleSearch API to obtain some additional information about the user. We have the following code:</p><div class="table-wrap"><table data-layout="default" class="confluenceTable"><tbody><tr><td data-highlight-colour="#ffffff" class="confluenceTd"><div class="code panel pdl" style="border-width: 1px;"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">...
if(usePeopleSearch)
{
    ResponseEntity&lt;Map&lt;String, String&gt;&gt; peopleResponse = peopleController.getPeople(kerberos);
    if(peopleResponse.getStatusCode() == HttpStatus.OK)
    {
        Map&lt;String, String&gt; peopleSearchMap = peopleResponse.getBody();
        memberMap.put(&quot;phone&quot;, peopleSearchMap.get(&quot;telephonenumber&quot;));
        memberMap.put(&quot;location&quot;, peopleSearchMap.get(&quot;l&quot;));
    }
}
...</pre>
</div></div></td></tr></tbody></table></div><p>However, it is possible that when we call the PeopleSearch API with supplied kerberos, the PeopleSearch API will throw an exception. When it happens, our code will display the following Internal Error exception to the user:</p><div class="table-wrap"><table data-layout="default" class="confluenceTable"><tbody><tr><td data-highlight-colour="#ffffff" class="confluenceTd"><div class="code panel pdl" style="border-width: 1px;"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">{
  &quot;timestamp&quot;: &quot;2020-02-06T14:36:05.309-05:00&quot;,
  &quot;message&quot;: &quot;Index 0 out of range [0..0)&quot;,
  &quot;details&quot;: &quot;uri=/rms/OC_GS/hierarchy&quot;
}</pre>
</div></div></td></tr></tbody></table></div><p>Being that this is anÂ Internal Error exception, the processing will stop. From the displayed message, it would also be impossible to determine what caused this error.</p><p>We can structure our code is such a way that we will catch an exception, log an informative error message, and allow processing to proceed:</p><div class="table-wrap"><table data-layout="default" class="confluenceTable"><tbody><tr><td data-highlight-colour="#ffffff" class="confluenceTd"><div class="code panel pdl" style="border-width: 1px;"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">...
if(usePeopleSearch)
{
    ResponseEntity&lt;Map&lt;String, String&gt;&gt; peopleResponse = null;
    try
    {
        peopleResponse = peopleController.getPeople(kerberos);
        if (peopleResponse != null &amp;&amp; peopleResponse.getStatusCode() == HttpStatus.OK)
        {
            Map&lt;String, String&gt; peopleSearchMap = peopleResponse.getBody();
            memberMap.put(&quot;phone&quot;, peopleSearchMap.get(&quot;telephonenumber&quot;));
            memberMap.put(&quot;location&quot;, peopleSearchMap.get(&quot;l&quot;));
        }
    }
    catch (Exception e)
    {
        logger.error(&quot;PeopleSearch request failed for kerberos: {}&quot;, kerberos);
    }
}
...</pre>
</div></div></td></tr></tbody></table></div><p>It the PeopleSearch API throws an exception, our code will be able to continue processing and log the error for possible future investigation. For example:</p><div class="table-wrap"><table data-layout="default" class="confluenceTable"><tbody><tr><td data-highlight-colour="#ffffff" class="confluenceTd"><div class="code panel pdl" style="border-width: 1px;"><div class="codeContent panelContent pdl">
<pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: java; gutter: false; theme: Confluence" data-theme="Confluence">2020-02-06 12:39:17.611 ERROR 9304 --- [nio-8081-exec-2] c.s.o.s.c.external.RmsController         : PeopleSearch request failed for kerberos: lougma</pre>
</div></div></td></tr></tbody></table></div><p>Unfortunately, there is no uniform method to process all kinds of exceptions. When we ask for non-existing data, some external API may throw an exception and others may return an empty list. We need to test the output of every external API we use and respond accordingly.</p><p>Also, we need to decide how to proceed in the face of exceptions. When we are generating long output and some piece of data is not available, we may choose to continue processing and log an error message. When we request a single piece of data which is not available, we want to display an informative message to the API user in the form of a custom exception.</p>
                    </div>

                    
                                                      
                </div>             </div> 
            <div id="footer" role="contentinfo">
                <section class="footer-body">
                    <p>Document generated by Confluence on Feb 12, 2021 23:35</p>
                    <div id="footer-logo"><a href="http://www.atlassian.com/">Atlassian</a></div>
                </section>
            </div>
        </div>     </body>
</html>
